### ISSUE TITLE
CircularSticksLoader bug?

### ISSUE THREAD

**Issue by ocsike** [agrawalsuneet/LoadersPack-Android#35] opened 2019-02-15 10:36 UTC
Hi,

I'd like to use the .CircularSticksLoader but I get this error:

`   java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                                                         at com.agrawalsuneet.loaderspack.loaders.CircularSticksLoader$scheduleTimer$1.run(CircularSticksLoader.kt:225)
                                                                         at java.util.TimerThread.mainLoop(Timer.java:555)
                                                                         at java.util.TimerThread.run(Timer.java:505)`

I use the examle xml code. I tried to use RingAndCircleLoader (example xml code) and it has no error.
What is the solution for this?

**Comment by agrawalsuneet** [comment] 2019-02-21 13:15
@ocsike will check and get back to you, if there is an issue you can expect the fix in just few couple of hours.

**Comment by agrawalsuneet** [comment] 2019-02-21 13:46
@ocsike I have fixed the issue here https://github.com/agrawalsuneet/LoadersPack-Android/pull/36 but I can't test it as I cannot reproduce the crash.
I was wondering if I can share you a new Android "aar" file with the fix, 
if you can put it locally and test and if it works fine, I will publish it.

Also, can you comment by tagging with the name as without that GitHub never notifies and I misses the update.

**Comment by ocsike** [comment] 2019-02-22 07:38
@agrawalsuneet The fix works fine :)

**Comment by agrawalsuneet** [comment] 2019-02-23 10:27
@ocsike will release it soon. you can verify and close this bug.

**Closed** 2019-02-23 13:52 UTC
Labels: Fixed, bug
